POST http://localhost:3001/auth/login
Content-Type: application/json

{
	"username":"juan",
	"password":"1234"
}

### Creamos un nodo en el grafo de neo4j (pegar token del primer POST)
POST http://localhost:3001/seguidor
Content-Type: application/json
Authorization: "Bearer" + eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWEyOGY0N2I0OGIxY2IyNmM0MTVmZTAiLCJ1c2VybmFtZSI6Imp1YW4iLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNTYwMTQ4MSwiZXhwIjoxNzA1NjA1MDgxfQ.M_Qg7y1ImzaZN1koGRSmWZBtnclLjy4r_4mGjl9UyeQ

{
  "idUsuario": "65a5224d00704a47ca02acef",
  "username": "ana"
}

### Creamos un nodo en el grafo de neo4j (pegar token del primer POST)
POST http://localhost:3001/seguidor
Content-Type: application/json
Authorization: "Bearer" + eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWEyOGY0N2I0OGIxY2IyNmM0MTVmZTAiLCJ1c2VybmFtZSI6Imp1YW4iLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNTYwMTQ4MSwiZXhwIjoxNzA1NjA1MDgxfQ.M_Qg7y1ImzaZN1koGRSmWZBtnclLjy4r_4mGjl9UyeQ

{
  "idUsuario": "65a5224d00704a47ca02ace9",
  "username": "juan"
}

###Juan sigue a Sara
POST http://localhost:3001/seguidor/seguir
Content-Type: application/json
Authorization: "Bearer" + eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWEyOGY0N2I0OGIxY2IyNmM0MTVmZTAiLCJ1c2VybmFtZSI6Imp1YW4iLCJyb2xlIjoidXNlciIsImlhdCI6MTcwNTYwMTQ4MSwiZXhwIjoxNzA1NjA1MDgxfQ.M_Qg7y1ImzaZN1koGRSmWZBtnclLjy4r_4mGjl9UyeQ

[{"username":"juan",
"idUsuario": "65a51734fa40779cbdb63506"},
{
"username": "ana",
"idUsuario": "65a5224d00704a47ca02acef" }]


###Obtenemos a los usuarios seguidos por Juan
GET http://localhost:3001/seguidor/seguidos/65a5224d00704a47ca02acef
Content-Type: application/json
