### Obtenemos comunidades
GET http://localhost:3001/comunidades
Content-Type: application/json

### Obtenemos causas
GET http://localhost:3001/causas
Content-Type: application/json

### Obtenemos acciones
GET http://localhost:3001/acciones
Content-Type: application/json

### Obtenemos usuarios
GET http://localhost:3001/users

### Obtenemos apoyos
GET http://localhost:3001/apoyo-causa
Content-Type: application/json


