version: '3.8'
services:
 mongo:
  container_name: mongo_container
  image: mongo:latest 
  ports:
   - 27017:27017
  environment:
    MONGO_INITDB_ROOT_USERNAME: "root"
    MONGO_INITDB_ROOT_PASSWORD: "mymongodb"
    MONGO_INITDB_DATABASE: "solidarian"
  volumes: 
   - ./data/mongo_data:/data/db/mongo
 mongo-express:
  image: mongo-express:latest
  container_name: mongo-express
  restart: unless-stopped
  ports:
   - 8081:8081
  environment:
    ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
    ME_CONFIG_MONGODB_ADMINPASSWORD: "mymongodb"
    ME_CONFIG_MONGODB_SERVER: mongo
 redis:
  container_name: redis_container
  image: redis:latest
  ports:
   - 6379:6379 
  volumes:
   - ./data/redis_data:/data/db/redis
 neo4j:
  container_name: neo4j_container
  image: neo4j:latest
  ports:
   - 7474:7474
   - 7687:7687
  volumes:
   - ./data/neo4j_data:/data/db/neo4j
  environment:
   - NEO4J_AUTH=neo4j/mypassword
   - NEO4J_dbms_default__database=neo4j-solidarian
  
 nats:
  container_name: nats
  image: nats
  ports:
    - 4222:4222